Testing again for threshold

diff --git a/.github/workflows/github_server.yml b/.github/workflows/github_server.yml
--- a/.github/workflows/github_server.yml
+++ b/.github/workflows/github_server.yml
@@ -24,16 +24,19 @@ jobs:
         npm run test -- --coverage --json
 
     - name: Check Test Coverage
-      if: always()
-      run: |
-        nyc report --reporter=text-summary --report-dir=coverage > coverage/coverage-summary.txt
-        COVERAGE=$(grep -oP '(?<=All files)\s+\K\d+%' coverage-summary.txt)
+      nyc report --reporter=text-summary --dir coverage > ./Linkify-src/coverage/coverage-summary.txt
+      if [ -f ./Linkify-src/coverage/coverage-summary.txt ]; then
+        COVERAGE=$(grep -oP '(?<=All files)\s+\K\d+%' ./Linkify-src/coverage/coverage-summary.txt)
         if (( $(echo "$COVERAGE < 80" | bc -l) )); then
           echo "Test coverage below 80%: $COVERAGE"
           exit 1
         else
           echo "Test coverage above 80%: $COVERAGE"
         fi
+      else
+        echo "coverage-summary.txt file not found"
+        exit 1
+      fi
 
 
 
